server:
  port: 8081
  tomcat:
    threads:
      max: 200

spring:
  application:
    name: shoeshop-dev
  # 1. Externalize sensitive database credentials
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/shoeshop
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    # 2. Optimize connection pooling (HikariCP defaults)
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL:20}
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    database: postgresql
    open-in-view: false # 3. Disable OSIV to save connections
    show-sql: true
    hibernate:
      ddl-auto: update # 4. Control table generation safely
    # 5. Fine-tune performance features
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 20 # 6. Fix N+1 select issue
        # 7. Optimize bulk inserts/updates
        order_inserts: true
        order_updates: true
        jdbc:
            batch_size: 30
  security:
    user:
      name: user
      password: 123123
  # 9. Config maximum page size
  data:
    web:
      pageable:
        default-page-size: 30
        max-page-size: 100
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      connect-timeout: 2s
      timeout: 2s
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 2s
  cache:
    type: redis
#Cache-Note: two ways to configure cache. We are using RedisConfig, so we donot need to configure cache here.
#    redis:
#      time-to-live: 1h    # Default TTL: 1 hour in milliseconds
#      cache-null-values: false # Do not cache null results
#End-Cache-Note:

# 8. Configure logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.tech.shoeshop: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

#project:
#  jwt:
#    secret_key: ${ACCESS_TOKEN_EXPIRATION}
#    access_token_expiration: ${ACCESS_TOKEN_EXPIRATION}
#    refresh_token_expiration: ${REFRESH_TOKEN_EXPIRATION}
